### ISSUE TITLE
Power loss / boards were disconnecting from the app

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#102]
During the pilot today the boards seemed to be disconnecting from the app very frequently. I was unable to test myself. The teacher noted the problem also happened in the morning pilot. He thought it was when they moved too far away - but the "far away" was about 2 feet. Students thought they must have hit disconnect. I'm not sure what was happening, but it was not disconnecting like this in the previous pilot (version 1.0.0 of the app) as far as I noticed.

I also saw the kindle shut off / go back to the lock screen at least twice. I couldn't tell if that was related. They had to reconnect when they turned it back on I think, so maybe? The other times, it just said it was disconnected and they had to scan again. Once it seemed like they had to power cycle the flutter to get it to scan and connect again.

**Comment by pdille** [comment]
No apparent direct cause for the source of what you saw, but the following 3 commits should help alleviate unintended user initiated disconnects:
1. 1fdf5b14
2. 1f557dc2
3. a8da4e26

Feel free to reopen if you run into this again.

**Comment by jenncross** [comment]
We have new reason to believe that this was being caused by a hardware issue (where the jack and the power brick plug were ever so slightly mismatched).

Reopening and changing to hardware issue.

**Comment by pdille** [comment]
@lczito @ehamner Now that all the boards have new power connectors, as well as the latest firmware, I'm curious if this is still a problem. I guess we'll find out after the next Pilot and then put a stake in this one.
