### ISSUE TITLE
Data Log Improvements

### ISSUE THREAD

**Issue by pdille** [CMU-CREATE-Lab/flutter-app-android#103]
A brain dump after using the Data Log page for a little bit. Probably should be separate issues (feel free to break them into ones), but I'm making them a task list for now.

- [ ] 1. When typing in the pop-up dialogs that bring up an onscreen keyboard, it's not clear how to close out of it since the keyboard covers the dialog action buttons
  - Kindle arrow button is the answer but does the average Flutter app user know this?
- [ ] 2. When recording time has finished, the main Data Log list does not update with the new set until I click Open log.
  - Also it should probably tell you it's done recording
- [ ] 3. When you've opened a data set, how do you go back to the main listing?
  - Kindle arrow button is the answer but does the average Flutter app user know this?
- [ ] 4. It's not clear that Send Log doesn't work because you first need to be viewing a log
  - Perhaps some pop-up message?
- [ ] 5. Delete a log you're currently looking at and you can still continue to view its data points
  - Seems...strange, yes? Perhaps kick the user page to the main listing page?

**Comment by ehamner** [comment]
Thanks Paul. I think you are right and we should avoid relying on the Kindle arrows or other buttons for any actions we want the user to be able to perform. Our target users can be 7 years old so we should spell everything out for them.

**Comment by SteveFulton95** [comment]
For number 1 and 3, any ideas as to how exactly let the user know how to do those actions?

**Comment by ehamner** [comment]
Can someone add a screen shot of relevant screens?

**Comment by SteveFulton95** [comment]
I moved these into separate issues.
