### ISSUE TITLE
When typing in the pop-up dialogs that bring up an onscreen keyboard, it's not clear how to close out of it since the keyboard covers the dialog action buttons

### ISSUE THREAD

**Issue by SteveFulton95** [CMU-CREATE-Lab/flutter-app-android#106]
Kindle arrow button is the answer but does the average Flutter app user know this?

**Comment by pdille** [comment]
I'm closing this because after thinking more about it more, the arrow key really is the way to go. It is _the_ standard for how Android does this (you will encounter it everywhere) and it's something that must be learned, so why not start young. ;-)
