### ISSUE TITLE
When you've opened a data set, how do you go back to the main listing?

### ISSUE THREAD

**Issue by SteveFulton95** [CMU-CREATE-Lab/flutter-app-android#108]
Kindle arrow button is the answer but does the average Flutter app user know this?

**Comment by mo11yj** [comment]
@SteveFulton95 I'm not entirely sure what you mean by main listing, could you explain the user flow a bit? You're right that I am not positive the average user would recognize the Kindle back button as the main navigation so if we need to add an "X" or another back arrow I can.

**Comment by SteveFulton95** [comment]
@mo11yj  I am just going to close this issue because it is very similar to #106 and @pdille closed that issue.
