### ISSUE TITLE
Scan Needs to Timeout (scans indefinitely)

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#11]

**Comment by jenncross** [comment]
5 or 10 seconds should be enough?

**Comment by tasota** [comment]
@ehamner do we still want this?

**Comment by pdille** [comment]
I'm actually in support of indefinite scanning in this case. As I mentioned in #33, a message comes up after 20 seconds on the Step 3 screen reminding the user to press the "Find Me" button if he or she doesn't see a Flutter in the name list. 

I also just added a timeout, where if the name list is empty for a minute it goes back to the Step 1/2 page (i.e. the first page the user ever sees)
