### ISSUE TITLE
Flutter name can be too long on the app landing screen.

### ISSUE THREAD

**Issue by SteveFulton95** [CMU-CREATE-Lab/flutter-app-android#110]
![screenshot_2017-03-14-09-05-54](https://cloud.githubusercontent.com/assets/8007178/23902332/26cde868-0897-11e7-95ac-e8244e45cc7d.png)

**Comment by ehamner** [comment]
I was curious... our longest possible name is 36 characters: Extraordinary Rainforest Tyrannosaurus

**Comment by pdille** [comment]
Bah, I overlooked that screen in my previous changes. Easy to fix though!

**Comment by pdille** [comment]
Fixed in commit 450a8a2
