### ISSUE TITLE
Rapidly minimizing and reopening the app while connected causes app to crash (kind of)

### ISSUE THREAD

**Issue by lczito** [CMU-CREATE-Lab/flutter-app-android#111]
If you are connecting to the app (still on the loading screen) and click the circle in the android menu, then relaunch the app less than 5 seconds later, the board thinks it has connected, the app does not know it is connected, the app crashes and reloads to a connection screen while disconnecting from the board.

In freetime, the problem is worse. The loading screen can be up for a longer period of time. When the app is relaunched from the freetime menu, the app crashes and returns to the freetime home page. Other outcomes have been a timeout error, followed by an app crash. This especially happened with boards that were connecting to the app for the first time. Once they connected successfully once, this issue did not occur unless provoked by the user.

**Comment by pdille** [comment]
Fixed in commit 337b98e and its followup f716c15
