### ISSUE TITLE
Name doesn't switch during weird reconnect on datalog page

### ISSUE THREAD

**Issue by lczito** [CMU-CREATE-Lab/flutter-app-android#112]
If you unplug the flutter board to force a disconnect on the datalog page, then go to reconnect with a new board, but minimize and reopen the app while it is still loading, the app reopens to the datalog page with the name of the old board. When you click the other pages, the name switches to the new name

**Comment by tasota** [comment]
this sounds similar to when we had the "Flutter Status disconnected" issue on the datalogs page. Maybe a similar root cause for bug?

**Comment by pdille** [comment]
@lczito This is low priority for the upcoming PD, but if you could help replicate again that would be awesome. I need your master QA skills. :)
