### ISSUE TITLE
Create an "advanced" color chooser

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#113]
Ideally uses something more interactive than the 3 sliders we were using before.

**Comment by jenncross** [comment]
Keep the palette but have a button for "more colors" out "advanced"

**Comment by tasota** [comment]
- [ ] Interface (xml designs)
- [ ] Code (Java Class)

**Comment by psdev1** [comment]
Added advanced color picker, but two issues need to be resolved.  The led does not display the exact color sometimes, and when a custom color is chosen in the control outputs dialog, it displays a blank swatch.
