### ISSUE TITLE
Make servo number labels clearer.

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#115]
Kids are not always clear which question mark in the app goes with which port number. 

Thoughts:
-Servo numbers could be bigger so they stand out more.
-Servo numbers are offset from the question marks. This confused one child.
-Number labels or icons could be more closely linked to the question mark in some way.
-The board itself could be clickable, not just the question mark. Some children click the text.
-Many of the children in this pilot could not read well, but did recognize icons and numerals. The fact that the locations on the app closely match the position of the port in real life was also helpful.

**Comment by mo11yj** [comment]
I updated the location of the servo numbers and added the icon to each number so it better matches the LED labels. I also agree that making the board clickable as well would likely help. https://zpl.io/Z2oUoew

![screen shot 2017-04-04 at 8 27 17 pm](https://cloud.githubusercontent.com/assets/25698542/24684588/1e440cc4-1975-11e7-855e-05376612ca76.png)

**Comment by pdille** [comment]
@mo11yj To me at least, it is a bit busy in that bottom left where we have an icon, the number 1, the word SERVOS, and then under that a sensor icon and it's corresponding text. Is it also clear to the kids that it's not just #1 that's a servo? Would it look weird to have the word SERVOS be written vertically, directly to the right of the numbers? You'd have to potentially tilt the kindle to read it if it's hard to do that mentally. Anyway, thoughts?

**Comment by mo11yj** [comment]
@pdille I agree that it is a little busy, the reason I did it that way was to match the board as closely as possible. However, I haven't seen the board layout in quite a while. If that has been updated I would want to update the illustration as well. Any chance we have a photo of the front of the board?

**Comment by pdille** [comment]
I don't think it's changed since you last saw, but here is a picture of the one I'm working off of:

![flutter](https://cloud.githubusercontent.com/assets/933363/25250095/4f62399c-25e2-11e7-8440-4ec4e19010e4.jpg)

**Comment by mo11yj** [comment]
Thanks for sending the image, I'll play around with repositioning the servos label and get back to you later this week, not sure if I will have time tonight or not.

**Comment by pdille** [comment]
@mo11yj: Were you still hoping to tweak the image? No worries if not. Thanks as always!

**Comment by mo11yj** [comment]
@pdille: sorry for the delay, I made an update to the image and uploaded it to zeplin. If you could drop it in and let me know if the screen seems less cluttered that would be great. 

https://zpl.io/Z2oUoew

![screen shot 2017-05-01 at 10 16 50 pm](https://cloud.githubusercontent.com/assets/25698542/25601690/ed5bd694-2ebb-11e7-9299-4bea7c9355c5.png)

**Comment by pdille** [comment]
Thanks, Molly!
