### ISSUE TITLE
Make timeout longer for "find me"

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#118]
During intro lessons "find me" kept timing out. Class needed more time there to allow for explanations.

**Comment by JSchapiro** [comment]
how long do we think it should wait? right now, it's 20 seconds.

**Comment by ehamner** [comment]
Let's try 1 minute?

**Comment by JSchapiro** [comment]
changed to 1 minutes with firmware v13
