### ISSUE TITLE
Make sensor port numbers bigger / bolder

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#120]
Kids could tell me what port number they had plugged a sensor in to. It was less clear to them what to do next on the sensor screen. 

Can the sensor port number be bigger/bolder/more obvious?

Can the question marks glow a little to make them stand out as the thing to click?

They do start to get used to this eventually, but in testing what was really obvious, for the Pilot 3 group, it wasn't immediately obvious what to do.

**Comment by tasota** [comment]
> Can the question marks glow a little to make them stand out as the thing to click?
See #121

**Comment by tasota** [comment]
would something like this help? (forgive my crude screenshot edits)

![sensor-numbers](https://cloud.githubusercontent.com/assets/9115672/24717660/4342b89a-1a01-11e7-81be-7eeff73fb87f.png)

**Comment by tasota** [comment]
Also revisiting #30 for sensor value font size

**Comment by tasota** [comment]
- Keep "Sensor" label, above a large sensor port number
- Sensor type written next to logo (like Light, Soil Moisture), and possibly keep "Set" keyword but in a different font color (to visually separate from a sensor that is already set)
- Make entire number/logo/text clickable (but not the progress bar for click-happy users)

![sensors](https://cloud.githubusercontent.com/assets/9115672/24719330/59075522-1a07-11e7-8b01-8881cb3f7eff.png)

**Comment by mo11yj** [comment]
Updated the screen to make the Set Sensor and number look much more like a button. I also removed the "Record data" and "Pause sensors" buttons from the bottom of the screen when there are no sensors defined. The screen was looking really busy with those buttons as well as the set sensor buttons. 

Zeplin Links:
No Sensors set: https://zpl.io/1Y6dWF
Some Sensors set: https://zpl.io/Z1g8XcT

![screen shot 2017-04-15 at 8 00 11 pm](https://cloud.githubusercontent.com/assets/25698542/25067607/88d39ad8-2216-11e7-8aac-764f0038f4b5.png)

**Comment by ehamner** [comment]
Not saying we have to do any of these, this is just what I was playing around with as a different idea
![2017-04-20 22 14 04](https://cloud.githubusercontent.com/assets/24419423/25259934/13f91148-2617-11e7-924e-298b8917114a.jpg)

**Comment by ehamner** [comment]
Also adding in the other two screen shots of options.

This is the one Katie preferred:
![screenshot_2017-04-20-15-43-27](https://cloud.githubusercontent.com/assets/24419423/25259986/57c4f2fc-2617-11e7-8ecf-0dc3dc7587a4.png)

![screenshot_2017-04-20-15-43-20](https://cloud.githubusercontent.com/assets/24419423/25259989/5b561ec8-2617-11e7-9cc4-577ddace284d.png)
