### ISSUE TITLE
Visually highlight the question mark when relationship config pop up opens

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#121]
Kids would open the relationship configuration pop up, and then randomly click so many places (off to the side, LED/servo config settings, the relationship type, etc.) It was crazy random clicking for Pilot group 3. Clearly clicking on the question mark was not a high priority. This was observed for multiple kids.

Try a visual prompt to make the question mark be highlighted when the relationship pop up first opens and no sensor has been selected. For example: a pulsing glow around the question mark.

**Comment by tasota** [comment]
Visual highlights on sensor tabs as well (see #120)
