### ISSUE TITLE
Coordinate tabs with their primary colors

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#122]
What if the tabs are wider with light versions of the colors for their tab, or if the words are in the color of the tab? During the class we often wanted to say you need to use "the blue" screen. That's controlled from the "green screen". But the color isn't visible until you click on the right tab.

**Comment by mo11yj** [comment]
Good call, I updated the menus to have colored text for each of the tabs. Updates are in Zeplin

**Comment by tasota** [comment]
https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a45432dcecc2cc9e06d

**Comment by mo11yj** [comment]
https://zpl.io/Z1TFY7y

Graphic assets for the new colored icons are available on this screen, for some reason it doesn't look like they populated throughout the full designs.

**Comment by tasota** [comment]
@pdille double-check background colors

**Comment by pdille** [comment]
Addressed in commit bb02f75
