### ISSUE TITLE
Try a new metaphor for connecting.

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#123]
Connecting to the flutter continues to be a sticking point for the class (as of Pilot 3). Even after they get Step 1, Step 2, and the name of their board is displayed, they do not realize it is a list and they need to select the name of their board to continue.

Lauren and I brainstormed ideas on the hour drive back. Our favorite:
Instead of flutter names appearing on the list, the image of the board flips over but it's name area is blank. Name tags appear above the board. Directions say something like  "Step 3: Tap your name tag" or "Step 3: Tap your Flutter's name". Name tag is then placed on the Flutter image to symbolize connection before screen switches to sensor screen (unless connecting from a different screen).

![2017-04-03 14 57 05 - copy](https://cloud.githubusercontent.com/assets/24419423/24626400/356da924-187f-11e7-9c68-211d94dac46e.jpg)

**Comment by pdille** [comment]
@mo11yj Any chance we can get mockups around this? I plan to dig into coding this next week. Thanks!!

**Comment by mo11yj** [comment]
New screens mocked up in Zeplin, I followed Emily's suggestion pretty closely, I like the idea and I hope that it will solve the issue of students not being able to connect their flutter. I am not entirely positive what the back side of the Flutter looks like though, so @ehamner (or anyone else), if you could post a picture that would be great, and I can make sure that my illustration and instructions match closely enough. 

![screen shot 2017-04-15 at 7 49 03 pm](https://cloud.githubusercontent.com/assets/25698542/25067528/c73eb7b4-2214-11e7-94e6-680dcc7bb62b.png)

Primary Screen:
https://zpl.io/ZQ71Jq

w/ Rescan tool tip:
https://zpl.io/Zn4UgL

**Comment by ehamner** [comment]
Not a perfect image since it's from a pilot, but I hope this helps: 
![back](https://cloud.githubusercontent.com/assets/24419423/25146513/20a0f2f2-2442-11e7-9378-c67761155775.JPG)

**Comment by mo11yj** [comment]
Thanks, that's really helpful, primarily I was curious if it was still a bare board on the back. I updated the tool tip text, but other than that I think the screen works well.

**Comment by ehamner** [comment]
There are also a lot of background colors currently because it's a prototype so we don't necessarily need to match that. I think the design looks promising.

**Comment by pdille** [comment]
@mo11yj If there are, let's say a dozen, Flutters trying to connect how do you want to handle that? Does the top list of names scroll left to right? Arrow buttons?

**Comment by mo11yj** [comment]
@pdille, I think arrows on the left/right are the way to go, I can mock it up later tonight when I'm home so you have assets.

**Comment by pdille** [comment]
Awesome, thanks Molly!

**Comment by mo11yj** [comment]
Zeplin links for design w/ arrows:
https://zpl.io/1NvU20
https://zpl.io/25upt7

**Comment by tasota** [comment]
@pdille  "Step 3. Tap Your Flutter's Name"

**Comment by lczito** [comment]
![p1000775](https://cloud.githubusercontent.com/assets/11083259/25194145/7d081cda-2507-11e7-9dd9-b814d9ce0f09.JPG)

**Comment by ehamner** [comment]
@mo11yj  here are notes from our meeting today. Can you please update the design for us? Overall, we wanted to try to make the images match the real boards a little more:

-All our tags are 2 line, so they are a fatter rectangle than in the current design
-white background, black text (green outline seemed ok)
-add feet to help make the image look more like the back (see photo from lauren)
-board orientation to match image above

-extra screen with label on the board after it has been selected. @pdille do you need an image of that?

**Comment by mo11yj** [comment]
Not a problem, I'll work on that this evening so you should have it before tomorrow morning @pdille.

**Comment by mo11yj** [comment]
Updated screens in Zeplin: 
https://zpl.io/ZQ71Jq
https://zpl.io/Jb4IJ
