### ISSUE TITLE
spacing of section headers in "Open Log" pop-up

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#129]
See the screenshot here:
![screenshot_2017-04-05-14-53-11](https://cloud.githubusercontent.com/assets/9115672/24721909/bfc848a4-1a0f-11e7-8f53-1e0e536061f0.png)

if one section has no logs (in this case, no logs under "Saved on device") how should this display? Should there be more space to indicate it is empty? Should a header only appear when there is something in the list?

**Comment by tasota** [comment]
steve removed headers for empty lists as well as added a dialog for when there is nothing at all, but are still considering using empty space to indicate an empty list instead of removing headers entirely? @ehamner

**Comment by mo11yj** [comment]
I think it would be nice to indicate that there are no logs available in either of the lists if that is the case. Especially if a student or teacher is expecting to find a log and have the wrong Kindle or something. I mocked up how we could do this and uploaded to zeplin. 

Zeplin Link: https://zpl.io/Z3hbBw

![screen shot 2017-04-15 at 8 14 32 pm](https://cloud.githubusercontent.com/assets/25698542/25067659/54302a88-2218-11e7-9275-db3755b7881d.png)
