### ISSUE TITLE
Modify data log email to be sent through our app instead of through a separate email client app

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#131]
Right now emailing data logs requires that email is setup on the kindles, which will be inconvenient for teachers to set up at best (and inaccessible through FreeTime mode at worst). 

Ideally, we would be able to send messages directly like Message from Me.

**Comment by SteveFulton95** [comment]
@jenncross Will the email addresses be the same for both sender and receiver?  As of right now, the UI only asks for the email address of whoever will receive the email.

**Comment by tasota** [comment]
@ehamner Paul and I were discussing implementing a solution similar to MFM for this. We can discuss this next week.

**Comment by tasota** [comment]
Also be sure to add a pop-up dialog for checking wifi connection, and also handling server error codes (and request timeouts).

**Comment by tasota** [comment]
@pdille 
request will be sent to http://fluttermail.cmucreatelab.org as a POST request with the following params:
"to" (the email recipient)
"body" (a message from the app user)
"data" (A tab-delimited list of CSVs)

Just let me know if you want me to change any of this to something else.

**Comment by tasota** [comment]
"flutter_name" (the flutter board's pretty name)

**Comment by pdille** [comment]
@tasota Is the name of the data log they created part of the data param? Would be good to name the file the same in the email as what they had created in the app.

**Comment by tasota** [comment]
adding it as parameter "data_name"
