### ISSUE TITLE
Navigating "Record Data" Dialog is covered by keyboard (unusable by kids, they don't use the "return"/"next" button at all)

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#132]
See screenshot images and suggestions in #126 

You cannot confirm the setup until the final textbox is filled in and the ">" next field button closes the keyboard.

Navigating between the textboxes is challenging with the keyboard up and most of the dialog is obscured (making completing the blanks in the sentence challenging).

Is there a way to make this more usable?

![image](https://cloud.githubusercontent.com/assets/11526803/24723495/c7f4fce2-1a15-11e7-9c7e-0cc5525f8a8a.png)

![image](https://cloud.githubusercontent.com/assets/11526803/24723496/cb452a3e-1a15-11e7-8cad-78abca8c86de.png)

**Comment by tasota** [comment]
This doesn't appear to be an issue anymore since we can click through fields now, although I could see us revisiting the design later.

**Comment by jenncross** [comment]
This is still a problem for the students... when the text is covered, the students do not know how to click the "Next" field button.

The motto that applies here "out of sight --- out of mind"

We need to either split the dialog in two, or implement the dialog as a linear dialog like in the earliest paper designs.

**Comment by ehamner** [comment]
A related observation, most kids I've observed seem to fill in the name last. If we're splitting it up we might consider putting the number of data points first and name second.

**Comment by pdille** [comment]
^ This happens to me too actually. The other fields are much more obvious and with the giant keyboard at the bottom it just diverts attention away from the small name field at the very top.

**Comment by jenncross** [comment]
In the redesigns, it would be nice if this data recording wizard and the #197 link creation wizards were similar.

**Comment by mo11yj** [comment]
![data-08a-record data - wizard 1](https://user-images.githubusercontent.com/25698542/27247240-da98e4e8-52c4-11e7-9379-b70524fbdb0e.jpg)
![data-08b-record data - wizard 2](https://user-images.githubusercontent.com/25698542/27247239-da986dba-52c4-11e7-8da6-3198719ec4c3.jpg)
![data-08c-record data - wizard 3](https://user-images.githubusercontent.com/25698542/27247242-da9ce0de-52c4-11e7-874e-2f22dac41306.jpg)
![data-08d-update data recording](https://user-images.githubusercontent.com/25698542/27247241-da99b15c-52c4-11e7-8f7b-de742c33bee1.jpg)

**Comment by mo11yj** [comment]
Here are my updates to the data recording set up screens. let me know what you think. I will add the screens to Zeplin, but am happy to update again if you notice any updates that may make the wizard more usable.

**Comment by ehamner** [comment]
There's a way to update a recording?

**Comment by jenncross** [comment]
@ehamner - Fourth screen shown above

**Comment by ehamner** [comment]
Right, but how do you get to it? I can't think of where that is in the app.

**Comment by jenncross** [comment]
Ok, gotcha. Yeah I'm not sure that the app/protocol currently supports that option either (which I think is totally fine ATM).
