### ISSUE TITLE
data log dialog scrolling

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#134]
Both the "Clean Up" and "Open Log" dialogs need to be scrollable between sections. We were able to scroll inside of the "this week" group but we could not reach the later group headers.

**Comment by SteveFulton95** [comment]
@jenncross maybe you were using an old version?  I could not replicate the issue.

**Comment by jenncross** [comment]
Very possibly. @ehamner - can you double check that the dialog does what you mentioned?

**Comment by ehamner** [comment]
It was probably the store release version 1.0.3 that is on most of our kindles and not the current development version. 

(As a side note, the development version usually has the same number as the previous release version which makes it hard to tell apart when we have it on a kindle. Would it be possible to increment the version after a release and mark it with a "d" until it's ready for the next release? I try to keep track, but with 16 kindles here I don't always manage.)

**Comment by pdille** [comment]
^ Yeah, I like that. 

@tasota I'd say from now on when we cut a branch to send to the store, the next master commit should be a version change to the next version but with the letter 'd' at the end, like Emily suggests.
