### ISSUE TITLE
After the spinner finishes, an error message appears in the Console

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#135]
Every time the flutter finishes connecting, I see this message appear in my console:

```
04-06 14:18:31.192 13537-13554/org.cmucreatelab.flutter_android E/FlutterAndroid: invalid number of arguments for READ_LOG_NAME=N,
```

Might just be an erroneous request that we don't even use?

**Comment by pdille** [comment]
Culprit is a call to globalHandler.dataLoggingHandler.populatePointsAvailable in method onFlutterConnected() of AppLandingActivity.java

Maybe the constructReadLogName message is being sent too early? I didn't look too much more into this. @SteveFulton95 ?
