### ISSUE TITLE
Data log button "Minimum" is squished on interface

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#145]
see image:
![screenshot_2017-04-19-14-52-59](https://cloud.githubusercontent.com/assets/9115672/25196963/47a0d8b2-2510-11e7-9506-7f34585b8dfe.png)

**Comment by SteveFulton95** [comment]
Resolved in commit e170296beeeb69bc724d581414675a9d2398038e
