### ISSUE TITLE
data tab hangs while recording values

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#148]
Seems to be somewhat sporadic behavior but consistently appeared while "Loading data points" on the data tab while the flutter board was still recording points. The protocol command requests are somewhat unpredictable too, at times we saw only 'P' and other times we saw 'R' request point numbers 0..n, then 0..n+1, then 0..n+2, etc.

**Comment by tasota** [comment]
While recording, you can enter another data log, and then click the "Open Log" button and this will enter a weird state. I just got mine to create like 20 of the same pop-up dialog.

**Comment by tasota** [comment]
Fetching a data log should not time out (See #66), but rather the app gets into a state where it keeps trying to read in points while the device is recording data.

**Comment by SteveFulton95** [comment]
@tasota I am not sure if this is any help, but I am intentionally polling the flutter every 5 seconds for the number of points available while recording.  This is so the app can load the data log once recording has finished.  Although, this will obviously change once #155 is resolved.

**Comment by tasota** [comment]
Good call. I think with #155 resolved this issue also disappeared. Since I can't replicate the issue anymore I'm closing it now.
