### ISSUE TITLE
Scale sound and soil moisture sensor readings

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#15]
From the hardware, 100 value is close, 0 value is far. Invert these so that 100 becomes far and 0 becomes close. 

Value does not hit the "close" 100% value ever - should be scaled for Sensor Tab to be sensitive for full value, and then convert back for storage on the Flutter.

Check w/ Josh or @chrisbartley for the scaling values used for sensors with Hummingbird.

**Comment by jenncross** [comment]
Chris didn't have properties files, so we may need to look at Hummingbird data sheets for the conversion we need.

**Comment by jenncross** [comment]
Okay so for the sensor value ranges and their mappings:

Duo-style Distance Sensor:   Near=72   Far=12 <<<< This is the one the students will get in future kits
Sharp-style Distance Sensor: Near=64  Far=8 <<<< This is what we have in the lab
Sound Sensor: Quiet=4 Loud=32
Knob: Min=0 Max=100
Temperature: Experimentally determine?
Light: Experimentally determine?
Soil: Experimentally determine?

**Comment by tasota** [comment]
I'm playing with one of the duo-style ones that Emily gave me from the pilot pile and I saw mine go as high as 77, and then I could get it as low as 1 (0, really, if nothing's there).

Also, when we say "invert" would it be sufficient to just switch the order of the adjectives? Seems a lot simpler than inverting the value itself (changing the input min/max isn't difficult though for what we'd need it for)

**Comment by tasota** [comment]
Used 0-75 as the new scale

**Comment by jenncross** [comment]
The sound sensor scale still needs to be fixed. Lauren experimentally found that the cap for one sensor to be 22 currently.

Also the moisture sensor seems to cap at 90.

**Comment by tasota** [comment]
Sorry, I didn't see the sound sensor when I was doing this before (and haven't actually played with one yet honestly).

So, right now the code has 0-75 on distance (plus inverted). And we would also want:
Sound: 0-22
Moisture: 0-90

**Comment by tasota** [comment]
I need to also note to myself that this isn't as trivial as just changing input min/max as we are tricking the users into thinking the range is still 0-100 (especially with having to invert the distance sensor values)

**Comment by tasota** [comment]
![get-paid](https://cloud.githubusercontent.com/assets/9115672/23223025/cc0663aa-f8f7-11e6-8b84-a331aaec0a61.gif)
