### ISSUE TITLE
Visually distinguish between no sensor plugged in and a sensor reading of "0"

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#150]
On the Sensors tab the data bars are empty and the value is "0" even when no sensor is selected. 

Visually distinguish between no sensor plugged in and a sensor reading of "0" both in the data value at the right and in the bar. Don't display the bar or display a disabled/inactive version. I generally prefer a disabled/inactive version whenever possible over hiding components. I think that would be preferred for the bar. It might be reasonable not to display a data value when there is no sensor chosen. We don't display a value for the empty sensor port on the robot tab so it seems consistent.

In at least one case kids saw a "0" reading and said "it didn't work" (when actually the light sensor was completely covered so the value was 0). This could make the distinction between a zero reading and no reading more clear.

May also help with understanding around issue #120

**Comment by pdille** [comment]
I'm going with not displaying a value when no sensor is chosen. Like you said, it matches the robot tab. Addressed in commit 8342cf5
