### ISSUE TITLE
check for a properly-formatted email on "Send Log"

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#151]
You can use something similar to that red marker for when the datalog time isn't properly formatted.

**Comment by tasota** [comment]
Also, the formatting doesn't need to be perfect. We just want to catch any silly mistakes when entering an email address (like forgetting to add the domain). Feel free to use a regular expression like the one in this javascript code snippet:

```
  var reString = "^[a-zA-Z0-9._%+\-]+@[[a-zA-Z0-9.\-]+$";
```

**Comment by SteveFulton95** [comment]
Resolved in commit c79379801c711981ba9af072c3a2abc2eaa12429
