### ISSUE TITLE
The sensor icons in data tab need to be lined up, both Vertically (to number columns) and Horizontally (with each other)

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#152]
See screenshot:
![screenshot_2017-05-02-12-55-33](https://cloud.githubusercontent.com/assets/9115672/25629384/56d5c29e-2f37-11e7-8650-9bdbdad8f681.png)

You can see the light bulb hangs lower than the analog sensor and no sensor icons (presumably that's from the line wrapping that's going on). So, try:

- Removing the text labels
- Increase the size of those icons
- Making sure the icons are in line with one another (horizontal)
- Make the icons line up with the columns in the data points list (vertical)

**Comment by SteveFulton95** [comment]
I solved this with just removing layout_gravity="center" and changing some margins.  Do we still want to remove the text labels and increase the size of the icons?

**Comment by tasota** [comment]
@pdille whatcha think? (or we can discuss on the hangouts calls later)
