### ISSUE TITLE
read output state is responding with a malformed value

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#153]
I'm seeing this response when sending a `Ob2` to my Flutter (Micro Olive Lizard):

```
V/FlutterAndroid: onFlutterMessageReceived -  Ob2 O,a,32,64,1,0,64,0#
```

I think I may have brought this up before but I'm not sure what would be causing it.

**Comment by jenncross** [comment]
Probably fixed by the new board
