### ISSUE TITLE
data log tab reads in points before saving to the tablet

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#155]
When opening the data log tab, we are immediately reading in the points from the Flutter's Log, and then we read them in again when clicking "Open Log."

Ideally, the app should only read in the points when the user wants to open the log (since this is the first time they are actually seeing the values in the Log).

**Comment by SteveFulton95** [comment]
@tasota If you have any questions about how I update logs just let me know. The structure that handles updating the logs is under the package helpers/datalogging.  If you want, I could take this issue. It should not be a huge issue to fix.

**Comment by pdille** [comment]
If you're willing, I say go for it! In the ideal world (and to get the most feedback) we'd get all all the open issues addressed for the upcoming pilot. I'll never turn down help, so if you have time, jump on in. But don't let it detract from finals/etc.

**Comment by SteveFulton95** [comment]
Okay, I'll claim this then.

**Comment by tasota** [comment]
@SteveFulton95 
![sagan-awesome](https://cloud.githubusercontent.com/assets/9115672/25804592/70545d7e-33ca-11e7-9bc6-d8e30c5d6456.gif)
