### ISSUE TITLE
Show both relationships for buzzer

### ISSUE THREAD

**Issue by lczito** [CMU-CREATE-Lab/flutter-app-android#157]
Show both the volume relationship icons and the pitch relationship icons on the robot page (even if one is set by default).

**Comment by tasota** [comment]
Looking at how the design is intended, I don't think we will be able to implement this for the pilot: https://app.zeplin.io/project/57f43918d127f7023581eaab/screen/57f43983b52e874f1c3ebb90

Alternatively, I could just add another image for now next to the volume one, representing frequency.

**Comment by pdille** [comment]
As discussed, go for the latter.
