### ISSUE TITLE
Add "Board" at the end of the Flutter graphic

### ISSUE THREAD

**Issue by lczito** [CMU-CREATE-Lab/flutter-app-android#165]
Change the board graphic so it says "Press "Find Me" on you Flutter Board"

**Comment by mo11yj** [comment]
Image updated, it can be pulled from Zeplin here: https://zpl.io/Z1TFY7y

**Comment by pdille** [comment]
@mo11yj: Thanks! It looks like the bottom shadow is cut off in this version though.

**Comment by mo11yj** [comment]
@pdille, Good catch, should be fixed now at the same link as above.

**Comment by pdille** [comment]
Thanks @mo11yj !
