### ISSUE TITLE
Create popup on data log screen

### ISSUE THREAD

**Issue by lczito** [CMU-CREATE-Lab/flutter-app-android#168]
When you click on the icons, have a pop up show up saying what port it was plugged into, what the icon is, and what type of sensor it is. The pop up should be called "Sensors for [log name]"

**Comment by SteveFulton95** [comment]
Am I describing the icon or just displaying the icon within the popup?

**Comment by pdille** [comment]
Since we no longer display the text under the icons now on that page, we'd want a description in there (i.e. the same text removed in an older commit)

If you could post a screenshot of what the new pop-up looks like that'd be great! Thanks!

**Comment by SteveFulton95** [comment]
![screenshot_2017-06-01-10-23-22](https://cloud.githubusercontent.com/assets/8007178/26684410/ed1211ba-46b4-11e7-9b48-f77cb8fe52f8.png)

**Comment by pdille** [comment]
That seems good. This was after clicking the middle column icon?

@lczito What do you think?

**Comment by SteveFulton95** [comment]
Yes, it was. It also works when you click the icons on the right hand side.

**Comment by ehamner** [comment]
I think it could also start with the icon in front of the sentence since elsewhere we pair up the icon with the words. Might make it look less like a warning message and help kids see it's not new information, but just more information about the icon they just touched.
