### ISSUE TITLE
When saving a data log to the tablet, save the name of the Flutter board that it was recorded from

### ISSUE THREAD

**Issue by pdille** [CMU-CREATE-Lab/flutter-app-android#170]

**Comment by pdille** [comment]
It may not *really* matter, but knowing which Flutter created that data set would be good. When you send the data via an email, the mail server automatically tags the email with the name of Flutter board. Problem is the name of the Flutter is sent from the current session on the app, which might not have been the Flutter that created that particular data set in the first place.

**Comment by SteveFulton95** [comment]
Do we want the name of Flutter to be displayed on the app, or is this just for emailing the data set?

**Comment by pdille** [comment]
Hmm, good question. Probably just for emailing purposes to keep things more simple. Look at the sendEmail* calls in onClickSendEmail of EmailDialog.java. We pass in the Flutter board name based on the session there but if we could pull it from the DataSet object that would be awesome.

**Comment by SteveFulton95** [comment]
I have a field in a data set for the flutters name now. I'll push the changes out later this afternoon. Although, I'm saving the flutters name to the actual .CSV that is saved on the Kindle, so old data sets won't be compatible. Should I use SharedPreferences instead? Or just continue to write the name of the flutter to the .CSV?

On May 5, 2017 12:08 PM, pdille <notifications@github.com> wrote:

Hmm, good question. Probably just for emailing purposes to keep things more simple. Look at the sendEmail* calls in onClickSendEmail of EmailDialog.java. We pass in the Flutter board name based on the session there but if we could pull it from the DataSet object that would be awesome.

**Comment by pdille** [comment]
What happens if an old data set is read in? Everything would still be read but this new Flutter name would be null? That's okay if so. I don't think data logs have been extensively used yet that we need to worry about that. We can just use "Unknown" as the name anytime these old logs are read in.
