### ISSUE TITLE
App crashes on data log tab if flutter is not connected

### ISSUE THREAD

**Issue by SteveFulton95** [CMU-CREATE-Lab/flutter-app-android#172]
I am not sure when this started occurring again, but I do know why.  At various stages while on the data log tab, progress dialogs are trying to be displayed.  However, if you have not connected to a flutter, you cannot use the SessionHandlers progress dialog methods because a session has not been started.

**Comment by tasota** [comment]
My most recent commits cb8580f044e84c9bf91da52396d1c100599076b9 59e7985744b50f4b448c7c00e7bc7ee7b7864d86 fixed this

**Comment by tasota** [comment]
My most recent commits cb8580f044e84c9bf91da52396d1c100599076b9 59e7985744b50f4b448c7c00e7bc7ee7b7864d86 fixed this
