### ISSUE TITLE
Fanciful Moonstone Horse - scanning issues...

### ISSUE THREAD

**Issue by JSchapiro** [CMU-CREATE-Lab/flutter-app-android#174]
It wasn't connecting at all to any kindle or any app. Both apps got stuck in the scanning state and eventually had up be shut down. Bluetooth was also getting turned off on the kindle. I tried restarting three kindles and that didn't work. I switched to another board and it connected to birdblox but not links.

**Comment by pdille** [comment]
Micro Olive Lizard (tasota's Flutter) is also very finicky about broadcasting. 

In stark contrast, Mini Lime Horse is a champ.

**Comment by JSchapiro** [comment]
tried power cycling, and connecting 10 times, and it worked every time...

**Comment by ehamner** [comment]
Interesting. Some of the Flutters in the pilot yesterday got disconnected while most were fine. Micro Onyx Lizard got disconnected once or twice and I saw this note and thought it was the same one for a second.
