### ISSUE TITLE
Emojis in log name show on main log listing page but when viewing the actual log they no longer appear in the title

### ISSUE THREAD

**Issue by pdille** [CMU-CREATE-Lab/flutter-app-android#185]
![12 pnqg png1](https://cloud.githubusercontent.com/assets/933363/26018822/1fb71410-373f-11e7-9a2d-f9485055d4de.png)

**Comment by SteveFulton95** [comment]
I believe this issue and #177 are related.  Through my testing, every emoji can be displayed.  However, only when I use multiple emojis do they start to have display errors.  For example, I can show 4 emojis in a row with no other text, but once I try to display 5 emojis in a row there is a display error.

**Comment by SteveFulton95** [comment]
According to the Flutter Protocol, a log name cannot be longer than 15 characters which explains #177.  

Are there other limitation to the text @JSchapiro?  For example, when I start recording with a certain amount of emoji's as the log name, the response of the name from the flutter is different from what I originally entered.

For example, I entered "☺☺☺☺☺☺☺" (21 bytes) as a log name.  When I request the log name from the flutter, the response is "☺☺☺☺☘" (15 bytes).

**Comment by JSchapiro** [comment]
as long as the log name doesn't have a carriage return in it, it should be just as passed in. of course, assuming it's 15 or less bytes.

**Comment by SteveFulton95** [comment]
Makes sense, thanks.
