### ISSUE TITLE
Make Paused state more obvious

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#190]
In one or two cases during the pilot kids had paused the sensors. Lauren was helping them try to figure out why nothing was working and it was not obvious that it was paused. I never even think to look for that.

Maybe the Pause/Play button could do something to indicate that it is in a paused state (blink, pulse, etc.) or there could be an indication somewhere else such as in the connection corner. If during pause nothing will actually go to or from the flutter, that might make sense. Maybe both locations.

**Comment by pdille** [comment]
We already have code to handle pulsing, so that might be the easiest. Also keeps focus on what UI element caused the change in the app.

Would be curious on your thoughts, molly.

**Comment by jenncross** [comment]
We have some new solutions for this. Making a new issue.
