### ISSUE TITLE
Hand tune LED color values to match screen images 

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#193]
The intensities of LEDs of different colors are different. This means that the straight RGB values that work on screens can be a bit wonky on the physical LEDs.

Let's go over each of the colors, and make sure that the LED color is a good match to the on-screen color.

**Comment by jenncross** [comment]
- [ ] ROSE
- [ ] RED
- [ ] ORANGE
- [ ] YELLOW
- [ ] CHARTREUSE GREEN
- [ ] GREEN
- [ ] SPRING GREEN
- [ ] CYAN
- [ ] AZURE
- [ ] BLUE
- [ ] VIOLET
- [ ] MAGENTA
- [ ] WHITE
- [ ] OFF (black)

**Comment by jenncross** [comment]
Blue is strong and needs to be scaled back through out.

| Color  | Red  | Green  | Blue |
|---|---|---|---|
|   |   |   |   |
|   |   |   |   |
|   |   |   |   |
|   |   |   |   |
|   |   |   |   |
|   |   |   |   |

**Comment by jenncross** [comment]
@SteveFulton95  - Hi Steve! Thanks for getting the dialog text for us. Do you think you could also get these colors for the LED color chooser and LED commands adjusted?

**Comment by SteveFulton95** [comment]
@jenncross  - Sure thing! So to clarify, you just want me to change the rgb/hex values that are sent to the flutter board and the colors on the color chooser, to the values that are listed in the above tables?

**Comment by jenncross** [comment]
Yes, that's right. By changing colors on both the Flutter and  the app we think they'll match better. Thanks!

**Comment by tasota** [comment]
From our dev discussion with @pdille @SteveFulton95, we decided to have the "true" LED values as the output values and the displayed ones calculated. Upon selecting a color in the ChooseColorDialog, the RGB value will be converted to its appropriate LED value.

Classes affected:
- MinColorDialog
- MaxColorDialog
- LedDialog
