### ISSUE TITLE
Progress Indicator? Count of data points when loading data off Flutter

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#195]
Can we get the total number of data points to be downloaded before starting to load them?

Could we get a count? E.g "Loading point 24 of 60" that updates so that we can tell if it gets stuck?

When the connection is lost, like in #161 during the data loading during initial contact with a Flutter, we get stuck on the loading screen.

**Comment by SteveFulton95** [comment]
Resolved in commit fd0e6fdacf7621f5e0728813ccb644a359e5edd1
