### ISSUE TITLE
Redesign of the servo indicator

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#196]
Servo indicator on robot tab does not look clickable. We think making a circle that matches the style of the LED might be more obvious?

We also need a servo indicator that can describe a range as described in the solution for #74 

Some ideas are shown below:
![office lens 20170602-162848](https://cloud.githubusercontent.com/assets/11526803/26743831/5964d1ac-47b1-11e7-9425-726ec3af0015.jpg)

**Comment by mo11yj** [comment]
![robot-13-sensordata-speaker-unmute](https://user-images.githubusercontent.com/25698542/27247741-87f05e42-52c9-11e7-820d-f60808154983.jpg)

Updated design in Zeplin here: https://zpl.io/1rWGOK

In the design, the numbers indicating the min and max position shouldn't move, e.g.: 

![screen shot 2017-06-16 at 7 26 03 pm](https://user-images.githubusercontent.com/25698542/27247755-b19f8402-52c9-11e7-8207-bc93cb12a7dc.png)

**Comment by tasota** [comment]
Just wanted to double-check the design choice with @pdille @jenncross @ehamner. See below. For constant, the value displays a tiny sliver for the servo angle. For the others, you see the range of values highlighted (Servo 3)

![screenshot_2018-06-14-13-29-09](https://user-images.githubusercontent.com/9115672/41428183-4d3a4840-6fd7-11e8-8bae-c13d65a4064d.png)

**Comment by ehamner** [comment]
Sounds right to me.
