### ISSUE TITLE
Create a wizard for link creation to scaffold process for students

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#197]
Resolution here: https://zpl.io/1lv1u6

**--------**
**Old Problem Discussion:**
> 
> _They do not recognize the need to click the "?" button and click just about everywhere else first.
> @ehamner says that they try to scroll and click outside the dialog before being told that they need to set the four attributes.
> 
> We have some ideas for improvement:
> 
> - Indicator to draw attention like a moving arrow, hand or bouncing ball type thing to follow along with.
> - Redesign to look extremely button like ... this needs to happen either way for the servo see #196  
> - Flash/Blinking indicator --- currently in use but still does seem to be eye catching enough
> 
> 
> 
> Related to #196 
> 
> Current app version view when making a new servo link:
> ![image](https://cloud.githubusercontent.com/assets/11526803/26744168/d70dea3e-47b2-11e7-98db-d89390a59bf0.png)
> 
> Current app version view when making a new LED link:
> ![image](https://cloud.githubusercontent.com/assets/11526803/26744173/db4fae7a-47b2-11e7-995d-e6d6c4d4ed1b.png)
> 
> 
> They do not recognize the need to click the "?" button and click just about everywhere else first.
> @ehamner says that they try to scroll and click outside the dialog before being told that they need to set the four attributes.
> 
> We have some ideas for improvement:
> 
> - Indicator to draw attention like a moving arrow, hand or bouncing ball type thing to follow along with.
> - Redesign to look extremely button like ... this needs to happen either way for the servo see #196  
> - Flash/Blinking indicator --- currently in use but still does seem to be eye catching enough
> 
> 
> 
> Related to #196 
> 
> Current app version view when making a new servo link:
> ![image](https://cloud.githubusercontent.com/assets/11526803/26744168/d70dea3e-47b2-11e7-98db-d89390a59bf0.png)
> 
> Current app version view when making a new LED link:
> ![image](https://cloud.githubusercontent.com/assets/11526803/26744173/db4fae7a-47b2-11e7-995d-e6d6c4d4ed1b.png)_

**Comment by jenncross** [comment]
@mo11yj  - would you be available to talk to us about any ideas?

**Comment by jenncross** [comment]
Following a discussion with @mo11yj @ehamner and @lczito, we are going to try to restructure this pop up as a wizard.

This will also permit us to complete issue #78 ... WOOOO!

**Comment by jenncross** [comment]
In the redesigns, it would be nice if the #132 data recording and the link creation wizards were similar.

**Comment by mo11yj** [comment]
I updated the screens in Zeplin, they start here: https://zpl.io/1lv1u6

I'm not going to post all the screen shots because there are like 15 updated pages, but let me know what you guys think. I matched this with the wizard for setting up a data collection, so you go through each step, then end on a page where you can review the settings before saving. 

From that last review screen, the user should be able to tap on any of the elements to go back to that section, and when they go back the "Next" button should become a "Review Link" and go back to the review screen, not the next screen in the wizard.

**Comment by jenncross** [comment]
Just emphasizing the second part of Molly's note, for how the review screen should operate (which I missed on first read):

_"From that last review screen, the user should be able to tap on any of the elements to go back to that section, and when they go back the "Next" button should become a "Review Link" and go back to the review screen, not the next screen in the wizard."_

**Comment by tasota** [comment]
Be sure to include #78

**Comment by jenncross** [comment]
- [ ] Implement the wizard from Zeplin

**Comment by jenncross** [comment]
![image](https://user-images.githubusercontent.com/11526803/38633790-b31c8360-3d8e-11e8-9e99-9e3b9ea7983a.png)

**Comment by tasota** [comment]
Broken up into several issues #235 #236 #237

**Comment by tasota** [comment]
Remove advanced settings gear icon on each step, but keep on the last/summary dialog.
