### ISSUE TITLE
Hard to get exact servo position

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#198]
Kid reported having a hard time getting the servo position to be exactly where he wanted.

**Comment by jenncross** [comment]
If we decide to fix this, maybe add +/- incrementing arrows for the number line.

**Comment by tasota** [comment]
- [ ] Interface (xml designs)
- [ ] Code (Java Class)

**Comment by tasota** [comment]
Go with increments of +- 1 degrees.
