### ISSUE TITLE
Kids do not recognize that their files are moved from the Flutter to the Kindle

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#199]
@ehamner observed one child who was particularly confused.
- He found his file under "Flutter Data" (or whatever that category is)
- He opened it.
- He clicked away to the robot tab.
- He clicked back to the data tab.
- He repeatably clicked in the space under "Flutter Data" where his data had been. (_On the grayed out text_) 😢 because that was where it was before and they do not read. But it was now under the "Kindle Data List"

There needs to be a strong visual indicator that it has moved. Maybe:
- As a moving graphic/animation like:
![image](https://cloud.githubusercontent.com/assets/11526803/26744935/46aa07f8-47b6-11e7-8aaf-4f05148324c6.png)
- Or an animation of their file moving from the "Flutter Data" list to the "Kindle Data" list.

**Comment by mo11yj** [comment]
Hi @jenncross, @pdille, getting back to updates and I don't quite understand what is happening here, could you send a couple screen shots representing the flow that the student filed? I"m not sure where he was seeing "Flutter Data", or how/when the data was transferred to the Kindle.
