### ISSUE TITLE
Most elements on the Robot page should be clickable (not just the circles)

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#2]

**Comment by tasota** [comment]
This is happening now on the Robots tab, but we need **Sensors** tab (icon and label).

**Comment by pdille** [comment]
This is fixed for the Sensor page, but not so for the Robot page. Renaming and pushing into the next milestone.

**Comment by tasota** [comment]
might want to wait for #115 with new flutter board image (so you can click the board's icons too)

**Comment by pdille** [comment]
@SteveFulton95 #115 is resolved pending slight modification to the image, but this shouldn't affect you making things clickable now. You should be good to go!
