### ISSUE TITLE
Design Pre-set data recording "short cuts"

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#201]
Students in Pilot 5 demonstrated mixed understanding of the data recording (2nd grade, end of the school year). When we asked for suggested improvements in the interviews, one student asked for a simpler way to set up data recording. For example "record 5 data points." 

We thought this idea was worth considering for ease of use for the youngest grade. Pre-set data short cuts that would record a reasonable data set, such as a one minute test, over night, etc. with a reasonable sample rate for the time selected.

Related to #132

**Comment by jenncross** [comment]
I like this idea! Some settings I could imagine:

(All providing about 50 samples)
Sample 60 times a minute for 1 minute
Sample 60 times an hour for 1 hour
Sample 2 times per hour for 1 day

**Comment by jenncross** [comment]
We could even sort them to be like:
Small (these will take a small number of samples)
- Sample 6 times a minute for 1 minute
- Sample 6 times an hour for 1 hour
- Sample 12 time a day for 1 day
Large (these will take a large number of samples)
- Sample 60 times a minute for 1 minute
- Sample 60 times an hour for 1 hour
- Sample 2 times per hour for 1 day

**Comment by jenncross** [comment]
Replacing this discussion with the issue / action item #253
