### ISSUE TITLE
Add images to error messages

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#203]
Many kids don't stop to read the error messages. They just immediately click out or some panic a little bit when faced with all the text and ask the nearest adult. I think having explanation text is reasonable, but I also think adding meaningful visuals would help. For most of our errors it's ok that they just click ok because the app behaves reasonably, but it might be nice for them to get a little more information from it.

For example, the error message that says you've been disconnected could have the image of the grey flutter with the grey Disconnected word as shown elsewhere in the app when the flutter is disconnected.

Could someone provide the list of current error messages that exist?

**Comment by jenncross** [comment]
@SteveFulton95  - Could you please pull for us a list of all of the prompts from dialogs with error messages and text prompts? For example, stuff like 'Flutter disconnected' and 'Data name already exists.' Just like a bulleted list with all of the text would be good.  Thanks!

**Comment by SteveFulton95** [comment]
@jenncross Yes, I will do that right now.

**Comment by SteveFulton95** [comment]
- Your tablet does not support Bluetooth LE - Closing application
- Unknown Device
- Your Tablet was not able to connect to your Flutter. Please try again.
- Your Flutter was disconnected from your Tablet. Please reconnect.
- To set up, please first connect your Flutter.
- To set up your robot, please first connect your Flutter.
- To set up sensors, please first connect your Flutter.
- Bluetooth is currently disabled. Press OK to enable it. Note that you cannot use Flutter without Bluetooth enabled.
- To record data, please first connect your Flutter.
- No Email App To Resolve Intent
- The Flutter is currently recording data. Do you want it to stop?
- Flutter Links is currently optimized for a large screen experience. Please use Flutter Links with a tablet that has at least a 640dp x 480dp screen.
- Must have a data log selected before you can send a data log.
- There must be data logs available if you want to clean up data logs.
- You are about to record a data log with 200 data points or more.  Loading this many data points onto your tablet will take a long time. Are you sure you want to continue?
- You need to be connected to WiFi before you can send a data log.
- You need to be connected to WiFi before you can send a data log.
- There was an error sending the data log. Please try again later.
- You cannot send a data log that is currently being recorded.

@jenncross If you want this in some other format, let me know.

**Comment by pdille** [comment]
@mo11yj: Ping on this, though no rush. Hopefully we don't need a unique icon for each of the above and there can be an array of general icons that cover these messages.

**Comment by mo11yj** [comment]
@pdille on the "Unknown device" error, which device is unknown in that situation? A BLE device that is connected to the Flutter?

**Comment by mo11yj** [comment]
Error icons in zeplin here: https://zpl.io/VO3wBQV

![screen shot 2017-08-25 at 8 14 42 pm](https://user-images.githubusercontent.com/25698542/29736739-3892e352-89d2-11e7-849f-e6194acf9d6c.png)

**Comment by jenncross** [comment]
- [ ] Add the above images (from Zeplin) to their respective error pop-ups

**Comment by tasota** [comment]
@tasota to split this up

**Comment by tasota** [comment]
Split up issue into #239 #240 #241 #242 #243 #244 #245 #246 #247
