### ISSUE TITLE
Cannot send a data log that is currently being recorded.

### ISSUE THREAD

**Issue by SteveFulton95** [CMU-CREATE-Lab/flutter-app-android#206]
I am assuming this happens because there is not an actual file that is created until we save the log to the kindle, which only happens once a data log has finished recording.

**Comment by pdille** [comment]
Tasota and I are in agreement that it doesn't make sense to ever send a log that's in the middle of recording. It looks like the UI lets you do this but then nothing is sent (looking at the logs it is failing). 

My vote is to display a message to the user that the log currently in progress cannot be emailed until it's completed.

**Comment by ehamner** [comment]
@pdille's suggestion seems reasonable to me.
