### ISSUE TITLE
Create new Simulate Data pop-up

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#208]
Similar to #209 and #210 from a discussion with @ehamner and @tasota 

Create a new pop-up for simulating data on the Flutter. This will:

1) Effect outputs using the simulate protocol 
2) Will not effect data that is being recorded. (Double check that this is the case and fix firmware as needed.)
3) Change the toggle button on the robot tab to a regular button.
4) This will influence the behavior of robot outputs.

Check out the sketch below:

![office lens 20170614-120853](https://user-images.githubusercontent.com/11526803/27143348-142d65aa-50fc-11e7-9f01-99ca1505bcb2.jpg)

**Comment by mo11yj** [comment]
Screen in Zeplin:
![robot-simulate sensors](https://user-images.githubusercontent.com/25698542/27774238-fd09193c-5f5b-11e7-9dca-51657af1ea49.png)

**Comment by tasota** [comment]
@SteveFulton95 do you want to work on just the XML of these popups #208 #209 for now? And then if you want to also work on the functionality just create a separate branch for that.
