### ISSUE TITLE
Create new Control Robot Outputs pop up

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#209]
Similar to #208 and #210 from a discussion with @ehamner and @tasota 

Create a new pop-up for "remote controlling" the robot's output during construction and testing.

1) Allow students to directly control servo position (sliders & maybe angle position indicators if there is room), LED color (color palette pop-up) and buzzer tone & volume (sliders & note indicator).
2) Use the "blocks" mode
3) Preserve existing links and sensor type in firmware
4) Add a button to the robot tab ("Control Robot Outputs")

Molly - could you please design a screen for this purpose? A rough sketch is below but the layout, spacing, and relative size needs some consideration. 

![office lens 20170614-120821](https://user-images.githubusercontent.com/11526803/27147607-690e447c-510b-11e7-90fe-59b7cc35b1dd.jpg)

**Comment by tasota** [comment]
> Use the "blocks" mode
This means setting output values directly in the protocol as opposed to creating links. Double-check with @JSchapiro but this should be safe to override links for output values until you clear the value and it will behave normally again.

**Comment by mo11yj** [comment]
Screens added to zeplin, let me know if I missed anything.

![robot-simulate data copy](https://user-images.githubusercontent.com/25698542/27774229-e3ff652c-5f5b-11e7-96bb-75be6c60ba22.png)

![robot-control outputs](https://user-images.githubusercontent.com/25698542/27774230-e7617606-5f5b-11e7-88fc-0e0f2f2f0593.png)

**Comment by tasota** [comment]
@SteveFulton95 do you want to work on just the XML of these popups #208 #209 for now? And then if you want to also work on the functionality just create a separate branch for that.

**Comment by jenncross** [comment]
- [ ] Add these revised pop-ups from Zeplin

**Comment by tasota** [comment]
- [ ] Interface (xml designs)
- [ ] Code (Java Class)

**Comment by tasota** [comment]
Makes sense to tackle #238 first

**Comment by tasota** [comment]
See Flutter Protocol doc under "Set output" (double-check with Josh and @jenncross)

**Comment by tasota** [comment]
👍
