### ISSUE TITLE
Displayed icons are not actually in memory; it will display as LED but if you do not set it again and save the link, it will overwrite to Flutter as nothing

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#21]
LED Dialog:
Displayed icons are not actually in memory; it will display as LED but if you do not set it again and save the link, it will overwrite to Flutter as nothing

**Comment by tasota** [comment]
from protocol:

Read Output state
Request: ‘Ooutput’
Response: ‘O,outputState’
Example:
Send: ‘Os1’
Return: ‘O,3A’ - servo 1 is at position 0x3A
Return: ‘O,x’ - servo 1 has no relationship set
Return: ‘O,p,0,b4,1,0,64’ - servo 1 has a proportional relationship with sensor 1. Output min of 0, max of 0x64, input min of 0, and max of 0x64
