### ISSUE TITLE
Create new Data Snapshot popup

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#210]
Similar to #209 and #208 from a discussion with @ehamner and @tasota 
Resolution for #205 and #190 

Create a new popup for taking a Data Snapshot (which is replacing the Freeze/Unfreeze and Play/Pause mechanic on the sensors tab).

It should:
1) Show all three sensor values and sensor types (and sensor numbers?)
2) Not effect the operation of the Flutter
--a) Not effect the data that is being recorded from the live sensors.
--b) Not effect the movement and responses of the outputs.

Sketch below:
![office lens 20170614-120837](https://user-images.githubusercontent.com/11526803/27148045-ee0561fa-510c-11e7-8685-5514d5808d83.jpg)

**Comment by jenncross** [comment]
Include a timestamp

**Comment by mo11yj** [comment]
New screens added to Zeplin!

![sensors-data snapshot](https://user-images.githubusercontent.com/25698542/27774217-a02dd5fe-5f5b-11e7-86f7-62ad58cc922e.jpg)
![sensors-02-filled](https://user-images.githubusercontent.com/25698542/27774216-a02a0d52-5f5b-11e7-8d29-1cf61739a02a.jpg)
