### ISSUE TITLE
Flutter disconnects when "Buzzer Volume" link set to Frequency, Amplitude, or Change type

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#212]
V1.1.1

When in the robot tab, create new buzzer link (volume tab). Select sensor 1 (Light), click to select relationship type, click on frequency, amplitude, or change type ---- > does not to the relationship creation pop-up....instead  we get a white screen and it changes to sensor tab with the "Connect Flutter - To set up sensors, please first connect your Flutter" error.

**Comment by jenncross** [comment]
Related to #213 

w/ Benevolent Olive Leopard and Flutter 16 (Kindle)

**Comment by tasota** [comment]
This appears to be a crash within the app code and crashes when setting to anything but Proportional or Constant. A stack trace should reveal the problem for #212 #213.
