### ISSUE TITLE
Make Step 2 of connection screen move immediately to step 3/4 after starting scan

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#215]
Right now, when you click "run scan" the Step 1/2 screen stays up until a device is discovered, which then reveals steps 3/4. Since there is no extra information gained after clicking "run scan" -- and the scan will run indefinitely -- immediately moving to Step 3/4 might make more sense.

**Comment by tasota** [comment]
NOTE: this will also automatically resolve other non-issues like the "Step 2" text jumping on the screen and the scan running indefinitely if no devices are ever discovered

**Comment by pdille** [comment]
Addressed in c059f96
