### ISSUE TITLE
Send Data Log dialog opens Get Data Log and also disconnects Flutter

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#222]
Send Data Log causes "Get Data Log" dialog to appear. I click send data log while viewing a log. After entering my email and sending the log, I get another "Get Data Log" dialog. When I click the button on that dialog, then the Flutter gets disconnected also. :(  I had just this one data log since I was trying to test the Send Data Log feature.

**Comment by pdille** [comment]
This is surely related to #220
