### ISSUE TITLE
Data log email sent twice

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#223]
I sent one one and received two identical email copies.

**Comment by pdille** [comment]
Did you initially have connection issues? (wifi, etc). This is most likely related to #178

**Comment by ehamner** [comment]
I only did the one test and it was when there was that other disconnect bug (#222) during the test, so I wonder if that caused it?

**Comment by tasota** [comment]
This is hopefully resolved in c0ea0d89d7fde588039f43d2abe5bd4891ae426a
