### ISSUE TITLE
Create an Advanced Flutter Settings/Control Page with Remove all links option

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#224]
- Accessed by clicking on the corner-connection indicator.

- When the corner is clicked, open the current connection status page.

- Add an advanced "gear" icon to that page.

- In the advanced icon, provide a "Reset Flutter" button.

- When the Reset Flutter button is pressed
-- Display a warning "This action will delete all links and sensor settings from this Flutter" and require "confirm" or "cancel"
-- Warn again and get second confirmation
-- Then call protocol
--- Remove relationships for all outputs, Request: ‘X’
--- Set all inputs to "not set" = 255. Request: ‘y,input,type’ Example: ‘y,1,255’

**Comment by tasota** [comment]
Playing with the update Parv implemented, I noticed that the "X" protocol command takes a long time to respond back to the app. This is something I think we should look out for with the new firmware (see #234).

Also @jenncross you should demo Parv's changes when you get a chance. I know you originally mentioned a double confirmation but it seems weird to me. Maybe with different wording?

**Comment by jenncross** [comment]
I think  just one pop-up confirmation following the "Remove/Reset" button press will be good.
