### ISSUE TITLE
Create Wizard for Buzzer

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#237]
Breaking up #197 into smaller issues.

**Comment by tasota** [comment]
- [ ] Interface (xml designs)
- [ ] Code (Java Class)

**Comment by jenncross** [comment]
I think we need to discuss a bit how to handle the dual volume-pitch nature of buzzer. Since the Wizard model doesn't lend itself to the current toggling method.

Volume Dialog:
https://app.zeplin.io/project/57f43918d127f7023581eaab/screen/57f4398abcb58ed62c8ab8f0

Pitch Dialog:
https://app.zeplin.io/project/57f43918d127f7023581eaab/screen/57f439882aa9cdb466f7ac18

**Comment by jenncross** [comment]
@ehamner @lczito @tasota @pdille  --- Can we discuss we want to approach the wizard for the buzzer? (This might be a good in-person discussion as it is a bit complex.)

Do we want to:
A) Have separate wizards for pitch and volume (and when we make a pitch link, it automatically creates a volume link and vice versa)
B) Have a single wizard where you first make a choice for whether the relationship you are creating is for pitch, volume or both
C) Have a single wizard where we always create two links (pitch and volume) during the process, so sensors are selected twice, relationship type is selected twice, etc.
D) Other?

**Comment by tasota** [comment]
Just wanted to ping everyone about this again because it will be coming up again soon. Thoughts?

**Comment by jenncross** [comment]
I lean towards option B above:

_Have a single wizard where you first make a choice for whether the relationship you are creating is for pitch, volume or both_

That first screen (the pitch/volume/both choice) of option B is currently missing from the Zeplin, but I think is simple enough to envision?

**Comment by tasota** [comment]
Sounds like we will have an option for which output you want to link (volume, pitch, or both). For both option, be sure to include a page that says "now we are going to set the VOLUME/PITCH" so the user understands what they are about to set the relationship/sensor/min/max for.

Jenn's scans from the discussion:

![img_20180718_152443](https://user-images.githubusercontent.com/11526803/42903565-3e9701f0-8aa0-11e8-9b7f-5b430b495930.jpg)

![img_20180718_152448](https://user-images.githubusercontent.com/11526803/42903574-450017d4-8aa0-11e8-8026-95755c585210.jpg)
