### ISSUE TITLE
Implement the buzzer mute/unmute toggle on the robot tab

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#238]
Please refer to note #3 on this Zeplin page:

![image](https://user-images.githubusercontent.com/11526803/41117934-6d5ea600-6a5c-11e8-9fb6-4ef9830f84d2.png)

https://app.zeplin.io/project/57f43918d127f7023581eaab/screen/57f43983b52e874f1c3ebb90

**Comment by tasota** [comment]
related to work in #209 but implement this one first.

**Comment by tasota** [comment]
Closing since live values for buzzer is now a separate issue
