### ISSUE TITLE
Make text on Connect Flutter list larger and green

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#24]
Flutter name text is hard to read and touch-target is small.

**Comment by jenncross** [comment]
See https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a3cd127f7023581f123

**Comment by jenncross** [comment]
Also make it green, following Molly's new design for making it look clickable.

![image](https://cloud.githubusercontent.com/assets/11526803/21024513/c9ebc938-bd52-11e6-8385-4bb430eeffb7.png)

**Comment by pdille** [comment]
Fixed in 615e9d3f
