### ISSUE TITLE
Missing corner tag indicating what flutter is connected

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#26]
See: https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f439aeb0e2e75712d94499

![image](https://cloud.githubusercontent.com/assets/11526803/20944844/0293fbf6-bbd3-11e6-94b7-daa912d9a3ea.png)

Clicking on that should return you to the Flutter connection tab for picking a new flutter.

**Comment by jenncross** [comment]
This is a duplicate now of #59

**Comment by jenncross** [comment]
Tab states on Zeplin:

Connect Flutter:
https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a46d127f7023581f131
Turn on bluetooth: https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a47d127f7023581f13c
Lost Conneciton:
https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a4b7b04d7602098c342
Connected:
https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a4cd127f7023581f149

**Comment by pdille** [comment]
Fixed in 024ae91
