### ISSUE TITLE
problem with servo background asset

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#260]
The angle for the servo background asset is a bit misleading. There are notches "close" to the middle of the 0-90-180 marks but not truly at 45 degrees. I think that users would expect these halfway markers to be at their proper diagonal positions (45 and 135 degrees). See image below

![link_servo_bg_lg](https://user-images.githubusercontent.com/9115672/42471492-dfa4ad5c-838b-11e8-8e2b-66259261514c.png)

Note the red mark where the 45 degree mark would be: 
![servo_middle](https://user-images.githubusercontent.com/9115672/42471538-0b3d01e4-838c-11e8-9a5d-cca792821393.png)

https://app.zeplin.io/project/57f43918d127f7023581eaab/screen/57f43992bcb58ed62c8abb1a

**Comment by jenncross** [comment]
I agree that it should be moved to 45 degrees. Perhaps we could ask Molly
to create the new graphic for us?

**Comment by mo11yj** [comment]
I'll update and send a new graphic this week.

**Comment by tasota** [comment]
I think we should put this asset change on hold for now (see #258).
