### ISSUE TITLE
make servo min/max match servo wizard

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#263]
The updated designs for the wizard are slightly different than the old screens to setting an Output's min/max value. Use these new designs for more consistency across screens.

**Comment by jenncross** [comment]
![img_20180718_145614](https://user-images.githubusercontent.com/11526803/42903651-8b4fd364-8aa0-11e8-993d-887ee4a8791c.jpg)

**Comment by tasota** [comment]
See also #265
