### ISSUE TITLE
make buzzer min/max match buzzer wizard

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#264]
The updated designs for the wizard are slightly different than the old screens to setting an Output's min/max value. Use these new designs for more consistency across screens.

**Comment by jenncross** [comment]
![img_20180718_152443](https://user-images.githubusercontent.com/11526803/42903565-3e9701f0-8aa0-11e8-9b7f-5b430b495930.jpg)

![img_20180718_152448](https://user-images.githubusercontent.com/11526803/42903574-450017d4-8aa0-11e8-8026-95755c585210.jpg)

**Comment by tasota** [comment]
Moved this comment over to #237 (the scans were related to that issue)
