### ISSUE TITLE
Buttons need to have shape rounded / fixed

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#29]
So that the button shapes are more like capsules:

![image](https://cloud.githubusercontent.com/assets/11526803/20944885/36085914-bbd3-11e6-979e-fbfc1fa9bf60.png)

Instead of rounded rectangles.

**Comment by pdille** [comment]
Fixed in commit e177347. Wrong git issue was referenced in that commit.
