### ISSUE TITLE
Text sizes should be larger on the Sensor tab

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#30]
![image](https://cloud.githubusercontent.com/assets/11526803/20944953/66e3fa48-bbd3-11e6-9668-d3635b9044a8.png)

Notably the name of the sensor type or "Set Sensor" should be a larger font and the sensor value should be larger,

**Comment by jenncross** [comment]
Also, very trivial here.... but the Sensor # and sensor name are left justified.

**Comment by tasota** [comment]
- Sensor Value
- Sensor Name

**Comment by pdille** [comment]
Fixed in commit e66496c

**Comment by tasota** [comment]
Could the sensor value font size still be larger? (see screenshot)

![screenshot_2017-04-05-13-03-45](https://cloud.githubusercontent.com/assets/9115672/24717760/8c5e0ee4-1a01-11e7-9a16-4b9393012ad3.png)

**Comment by pdille** [comment]
Made larger still in commit 8342cf5
