### ISSUE TITLE
Implement a No Flutter found page

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#33]
Once #11 is implemented, we will also need a No Flutter found indication.

Seen here:

![image](https://cloud.githubusercontent.com/assets/11526803/21024400/5ffd4cae-bd52-11e6-9c1f-9dd6643aec13.png)

**Comment by tasota** [comment]
See #123 as well about the new connection screen

**Comment by lczito** [comment]
We might not need this page. Instead, we could try returning to the original connection page with step 1 and step 2. Students seem to be getting confused by additional screens

**Comment by pdille** [comment]
After 20 seconds a message comes up on the Step 3 screen reminding the user to press the "Find Me" button if he or she doesn't see a Flutter in the name list. Once the initial scan button is pressed (Step 2), it'll keep scanning as long as it remains on the Step 3 screen.

The above, combined with now a timeout of 1 minute on the actual Flutter board, should hopefully negate the need for more screens. I agree about minimizing the number of new screens we show. I'd also be curious of the students' experience in Pilot 5 though.

Lastly, I just added a timeout where users are sent back to the Step 1/2 screen after a minute of no Flutters being added to the name list. (referenced in #11). Basically, exactly what you suggested above. :)
