### ISSUE TITLE
change replace color chooser sliders with palette

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#35]
Swapping out the color sliders with palettes with the 12 pure RGB primary/secondary/tertiary hue colors + black and white).

https://simple.wikipedia.org/wiki/Color_wheel#The_12_major_color_wheel_colors_color_comparison_chart
![image](https://cloud.githubusercontent.com/assets/11526803/21110949/5772764a-c06d-11e6-8613-5b032c00731d.png)

That will move the color count up to 14, (but it looks like there is room for the extra two swatches in the dialog layout below).

1. ROSE
2. RED
3. ORANGE
4. YELLOW
5. CHARTREUSE GREEN
6. GREEN
7. SPRING GREEN
8. CYAN
9. AZURE
10. BLUE
11. VIOLET
12. MAGENTA
13. WHITE
14. OFF (black)

---
Refer to the general layout of:
Molly created this palette-only mock up in Zeplin https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f4398e47613d865b721e2c
![image](https://cloud.githubusercontent.com/assets/11526803/21110583/c1ed1d74-c06b-11e6-8b6e-76c7caebfa81.png)

**Comment by jenncross** [comment]
We would probably want Molly to modify it to match our style and make the swatches big enough to click with a finger.

**Comment by jenncross** [comment]
Though the outside edge colors are pretty indistinguishable from an "OFF" LED so maybe just remove the two outside layers of options and just have a off/black swatch available.

**Comment by jenncross** [comment]
Molly created this palette-only mock up in Zeplin https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f4398e47613d865b721e2c
![image](https://cloud.githubusercontent.com/assets/11526803/21110583/c1ed1d74-c06b-11e6-8b6e-76c7caebfa81.png)

However I would suggest swapping out the colors in the palettes (which are attractive on screen, but dull on the tri-color LEDs with the 12 pure RGB primary/secondary/tertiary hue colors + black and white).

https://simple.wikipedia.org/wiki/Color_wheel#The_12_major_color_wheel_colors_color_comparison_chart
![image](https://cloud.githubusercontent.com/assets/11526803/21110949/5772764a-c06d-11e6-8613-5b032c00731d.png)

That will move the color count up to 14, but it looks like there is room for the extra two swatches in the dialog.

**Comment by ehamner** [comment]
I think the 14 colors Jenn listed make sense. Black and white can always go at the bottom and it should look ok.

**Comment by jenncross** [comment]
PS That table on wikipedia also references the color HEX (for making the interface) and the color RGB for sending to the Flutter.
