### ISSUE TITLE
BLE message sending

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#49]
The proper way to send multiple messages to the Flutter is to send one message at a time, waiting for a response before sending the next one.

Right now, we just use a 300ms delay between sending the next message. This works for now, but isn't the "safest" way to do it.

**Comment by SteveFulton95** [comment]
Do we not already wait for a response? There is an onReceived callback method that will get called after the Flutter receives a message and will send us a response - public void onReceived(final byte[] bytes).

Within that callback method I have a queue that will then send more messages one at a time (it will poll the queue).  Even though I wait until that callback method is called to send another message, there are still some errors with certain messages never seeming to have been successfully received or processed in someway.  Like an LED for example.  Without that delay, if I were to set an rgb value of say (100,100,100), the only LED to be successfully set was the last one (blue).

It is almost like the callback method onReceived is called before the Flutter has finished processing the last message.  So then when we send a new message, the Flutter stops processing the last message, and deals with the new one.

**Comment by tasota** [comment]
No, you're right. Your code was calling again after receiving. This is mostly a note for myself on my branch from the changes that I've made

**Comment by tasota** [comment]
We should keep this in mind though when updating it again. We might still need some delay after receiving data from onResponse

**Comment by tasota** [comment]
This is resolved now, and we have the delay set to 100ms now (though it's likely that even this could be smaller if we really wanted it to be; figured we'd keep it just to avoid spamming the device with messages).
