### ISSUE TITLE
make "simulate data" units consistent with sensor values/units

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#52]
Simulate Data shows numbers as unitless values and simulate data shows a percentage .... make these consistent?

@lczito @ehamner  - which should it be? values or percentages? I'm leaning towards percentages (as being more accurate and eliminating the question "percent of what?")

**Comment by tasota** [comment]
we can save simulated data for after the january milestone

**Comment by tasota** [comment]
I will update this with #141
