### ISSUE TITLE
simulate data vs play/pause

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#53]
@lczito @ehamner 

So some issues arose with implementing simulated data to consider....

1. No way to send "sensor values" to the firmware in protocol
   a.  Work around could be to just quickly set the output state as "constant"
   b. That would be taxing on speed of communication for "simulating" well

2. How would we "simulate" data for other relationship types? --- most challenging to do "change" or "cumulative"
    a. That would require a full simulation of the Flutter relationships in the app.... which is even messier

3. Proposed solutions:
    a. Switch out "simulate" data for the original "Play/Pause" idea, which allowed the robot to be "paused" to permit physical modifications
   b. Switch out "simulate" data for "test/demonstrate" mode which exhibits the full range of the output values/links
   c. Only permit simulation for proportional, amplitude and frequency modes?
   d. Encourage users to first build the robot with knobs, to permit data simulation with different sensors?

**Comment by tasota** [comment]
This was mentioned in our meeting again today and will be worth discussing more at some point.

**Comment by jenncross** [comment]
Let's try the following set of solutions for detangling these systems:
1) Simulate Data #208
2) Control Outputs #209 
3) Data Snapshot #210

Feel free to reopen this needs more discussion.
