### ISSUE TITLE
Implement buzzer default relationship type as constant relationships

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#54]
Requires #48 

- [ ] Use default constant volume (100?) when pitch relationship is made
- [ ] Use default constant pitch (220?) when volume relationship is created

... these are then overwritten if both pitch and volume have assigned relationships

**Comment by tasota** [comment]
For v1.0.0, we cheated this for volume by doing a range of 100-100 but didn't do it for pitch (I think pitch ranges by default still).

We could implement this before #48 is done by doing the same for pitch, and then replace with constant later if we really want to.

**Comment by jenncross** [comment]
This is the fix for issue #72 also.

**Comment by tasota** [comment]
Ended up using 440 Hz as per the suggestion in #72
