### ISSUE TITLE
Issues (slow?) reconnecting to a Flutter

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#55]
Reconnecting requires and extra "Find Me" cycle or power cycling Flutter

- Start with Flutter (Cheesy Orange Lizard) connected to Kindle (Orange Fire)
- Back out to disconnect
- Click Scan
- Click Find Me
- **Fluter does not show up on list while "Waiting" light is lit first time**
- "Waiting" light turns off
- Click "Find Me" button again
- Wait a little, and Flutter (Cheesy Orange Lizard) shows up this time
- Select on list and connect

**Comment by jenncross** [comment]
Repeatable with Olive Micro Lizard(?)

**Comment by tasota** [comment]
Also power-cycling seems to work the first time again (after going back to force DC)

**Comment by tasota** [comment]
I'm at my apartment right now and can't manage to replicate this issue now, regardless of how I disconnect (hitting back button or force-closing the app)
