### ISSUE TITLE
Replace "Red/Blue/Green" values with color names

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#56]
Use color names from color swatches once #35 is implemented

1. ROSE
2. RED
3. ORANGE
4. YELLOW
5. CHARTREUSE GREEN
6. GREEN
7. SPRING GREEN
8. CYAN
9. AZURE
10. BLUE
11. VIOLET
12. MAGENTA
13. WHITE
14. OFF (black)

**Comment by jenncross** [comment]
Might want/need to shorten 5. CHARTREUSE GREEN to Yellow Green or Lime Green for line wrapping?

**Comment by tasota** [comment]
I'll take this one since I was the one who half-finished it... lol
