### ISSUE TITLE
Display app version number

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#57]
The kindle doesn't make it very clear what version of an app you are running. The easiest way seems to be to go to Apps > Library and then you can see the version number of the installed app. but you have to be in the adult side of the kindle (not the kids' free time). I think we'll want an even more obvious way confirm that the app running on the kindle is the correct version number as we push bug fixes during pilots. 

I suggest a small version number at the bottom of the grey menu on the left.

**Comment by jenncross** [comment]
Another option would be to create an about screen accessible via the hamburger.

**Comment by jenncross** [comment]
Need to have a "ABOUT" or "SETTINGS" page designed

Should include:
- Open-source License information
- Version number
- "created by Carnegie Mellon CREATE Lab" or similiar
- Link to a Flutter website


Perhaps based on:

![image](https://cloud.githubusercontent.com/assets/11526803/22761007/f371b5ec-ee26-11e6-8f16-1d37bc47b586.png)

https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=580243918ef61b0e14e0071c

**Comment by pdille** [comment]
Fixed in 15c12b13
