### ISSUE TITLE
Implement "Flutter Status Page"

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#58]
See Zeplin: 

https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a4e7b04d7602098c39d

https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a497b04d7602098c2fb

https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f439aeb0e2e75712d94499 (note number 4 in the top right corner)

When there are issues, we can't restart the app if we are running in Free Time and it's not obvious to those unfamiliar with kindle how to cancel the app even outside of Free Time. It's also hard to switch which flutter the kindle is connected to in the middle of use.

**Comment by jenncross** [comment]
![image](https://cloud.githubusercontent.com/assets/11526803/22758577/4074d112-ee1d-11e6-814b-bb11e3b7c747.png)

This is important for fixing #59 since clicking that tag needs somewhere to go.

**Comment by pdille** [comment]
Fixed in 024ae919
