### ISSUE TITLE
Add "Connect Flutter" button in the top-right corner of the Activities

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#59]
See image: 

![image](https://cloud.githubusercontent.com/assets/11526803/21660824/1ae6d74a-d29f-11e6-83e4-52802977c2bb.png)
https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a3bc8c9905965c0d02e

**Comment by lczito** [comment]
Right now, the only way to disconnect is to quit the app or unplug the board. If you are in freetime, you cannot quit the app (the little square disappears).

This also seems related to #26

**Comment by jenncross** [comment]
Blocked by #58

**Comment by jenncross** [comment]
Tab states on Zeplin:

Connect Flutter:
https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a46d127f7023581f131
Turn on bluetooth: https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a47d127f7023581f13c
Lost Conneciton:
https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a4b7b04d7602098c342
Connected:
https://app.zeplin.io/project.html#pid=57f43918d127f7023581eaab&sid=57f43a4cd127f7023581f149

**Comment by pdille** [comment]
Fixed in 024ae919
