### ISSUE TITLE
Recording set up dialog words do not look clickable

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#61]
When setting up the recording, the word "minute" does not look clickable. Also the drop down arrow is really far away to the right (several inches away from the word).

**Comment by jenncross** [comment]
See dialog design here:
![image](https://cloud.githubusercontent.com/assets/11526803/22668066/5c41f88e-ec8d-11e6-95c8-8ca1f66af765.png)
