### ISSUE TITLE
When you start recording, kids want a confirmation

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#62]
When you start recording, the kids want a confirmation that recording has started. They don't notice the light on the board (though it is good to have and does confirm that the board is recording). Multiple times kids started setting up recording again. Some sort of message is needed. Perhaps it could say:

Recording started.
Flutter will record data until [time].

[Ok button] [maybe a Cancel Recording button??]

**Comment by mo11yj** [comment]
https://zpl.io/Z2nihWH - Link to new screen

Added a dialog in Zeplin to show once the student taps "Start Recording"

![screen shot 2017-02-18 at 8 08 31 pm](https://cloud.githubusercontent.com/assets/25698542/23098178/0b5f5168-f616-11e6-84e7-05aad71dff38.png)

**Comment by SteveFulton95** [comment]
Resolved from commit 9fac804f5bf8d1b423307651a34d56f258ec6fb7
