### ISSUE TITLE
Warn if current recording will be overwritten

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#63]
When they open the recording dialog to set up a recording, check if the connected board is currently recording data. If it is warn them.
Something like:
 "The Flutter is currently recording data. Do you want it to stop?"
[Stop the current recording] [Keep the current recording]

Molly are there standard ways to phrase this so it's not confusing?

**Comment by SteveFulton95** [comment]
I am going to reopen this issue since I don't think we decided on the wording.

**Comment by mo11yj** [comment]
Here is my initial take, but I am not sure the wording is exactly right yet, In this case, do we think teachers would want them to get a new flutter? or overwrite the recording? I'm not positive I understand the use case well enough to get the wording prefect. Happy to chat more about this.
 
![screen shot 2017-02-18 at 8 18 30 pm](https://cloud.githubusercontent.com/assets/25698542/23098280/f1dd4e50-f617-11e6-973a-1986c4c05120.png)

**Comment by mo11yj** [comment]
Also, is it possible to pull the name of the data set that is currently recording off the Flutter? If so, I think listing the actual name of the set could help a student or teacher determine what or who is recording.

**Comment by mo11yj** [comment]
I think this and issue #68 can be solved together. See my comments on issue #68.
