### ISSUE TITLE
Students and teacher are not clear that they have to connect to the Flutter to download data

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#64]
Students and teacher are not clear that the have to connect to the Flutter to download data. If they are no longer connected when data collection completes, they frequently didn't realize they needed to reconnect to get the data from the Flutter board.

**Comment by jenncross** [comment]
This might be a instruction / training issue, that could be remedied making sure teachers understand that the Flutter disconnects when the app /tablet is shut down. And make sure that they understand that newly downloaded data, sensor readings and links cannot be processed if their is no Flutter connected.

**Comment by ehamner** [comment]
After today I have more clarity on why this is so confusing! This is how it is working currently:
1) Under the title Open Log, there is an orange bar that says "On <name of flutter you are connected to>" but you can't click it.  You also can't click the bar that says "Saved on device". I think looking at the design those are just supposed to be labels.
2) If you record data for one minute, for example, at the end of the minute when the red light on the flutter goes off you can't get the data even though you are connected to the flutter. If you want the data, you have to close the app (using the square in the bottom bar, only available when not in free time) or turn off the flutter to force a disconnection, then reconnect. When you come back to the data log tab, the data log from the flutter will be listed and available to click on to open. 

The design was intended for this to be the landing screen of the Data tab:
![data-00-landing-openlog](https://cloud.githubusercontent.com/assets/24419423/22754861/f2d023fc-ee0e-11e6-9a41-2368df3e987e.png)

The problem is, even if you check for a connection when you first open the tab (and populate the list), if you stay on the tab after setting up a recording, you need to keep checking for a log to exist on the connected flutter. If that check is easy to add, let's add that. If those checks are going to cause problems or slow things down then plan B would be to have the Data landing page be blank with only the buttons on the left.

**Comment by SteveFulton95** [comment]
On my branch the data logging tab has been improved a lot. I am not sure if it is enough of a fix to this problem.

It will populate the data logs without having to close out of the app.  However, you have to either click the Data Log tab on the left hand side or click the "Open Log" option which pulls up a dialog according to the zeplin project.  So this will not display the data log automatically, there will have to be some sort of user interaction to refresh the list.  Is this a good enough fix?

Also, when a user does refresh the list of data logs, an incomplete data log will be displayed before it has finished logging as long as one data point has been recorded. Not sure if that is a good or bad feature. Thoughts on that?

**Comment by jenncross** [comment]
Hi Steve - the load of partial logs was the intent of the original design. So that should be good! We might want to consult Molly on how we should indicate to users that it is a partial/in-progress log (as a note/pop-up/icon etc.) if that is not currently in the design.

**Comment by ehamner** [comment]
Related to issue 69 (how do I do that in github?). 

Your new functionality sounds like a definite improvement, but I think we still need to either either check for logs or not display the list.
