### ISSUE TITLE
Time out if data download fails

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#66]
One time the data download failed and just kept spinning (for ~10 minutes). When we went back (little arrow at the bottom of the screen), and tried again, it took about 10 seconds. App should time out at some point.

**Comment by jenncross** [comment]
Do we need an error message designed?

**Comment by mo11yj** [comment]
Dialog added to Zeplin, I tried to create wording that might be a little more Kid friendly than a traditional time out error, let me know what you think. 

![screen shot 2017-02-18 at 8 36 40 pm](https://cloud.githubusercontent.com/assets/25698542/23098417/a30c55c0-f61a-11e6-962f-57802408ef2d.png)

**Comment by tasota** [comment]
I think this might have been related to issue #98 which I just added.

**Comment by tasota** [comment]
I think this is related to #148. Right Now I am watching this spin indefinitely as it continues to make requests until the data recording finishes.

After it finished recording, it tried reloading all the data points, but then nothing showed up on the lists. Then i reclicked the data log tab and it populated properly.

**Comment by tasota** [comment]
With #148 and #155 resolved this should no longer be an issue. Any hangups with receiving Flutter data should now be caught with a dialog box as per #119.
