### ISSUE TITLE
The blank 0/0/0 data points are a little confusing

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#69]
The blank 0/0/0 data points (where data was expected but not yet recorded, I think) are a little confusing but they were able to get past it (2nd grade class). Teacher had to keep explaining it to each group.

**Comment by lczito** [comment]
Maybe there can be dashes instead of zero's? Or something can be added to the name so students are aware that the data set is incomplete? This also seems related to #64

**Comment by SteveFulton95** [comment]
I think that was a bug. I made the blank 0/0/0 data points as a temporary fix to Data Points that were corrupted some how. It may be caused if the flutter was turned off in the middle of data logging (I could be wrong though). I've been testing the data logging tab a lot on my branch and I no longer have this issue, though.  I won't close this issue until we are 100% sure.

**Comment by tasota** [comment]
Not sure if the issue was "resolved" but closing this anyways since josh updated the firmware to immediately record a data point when it starts recording anyways (so users won't run into this issue).
