### ISSUE TITLE
Default to Question Mark for unknown sensors

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#7]

**Comment by jenncross** [comment]
(right now, it just says “No Sensor” which can be confusing)

**Comment by jenncross** [comment]
![image](https://cloud.githubusercontent.com/assets/11526803/21024113/55ce4b30-bd51-11e6-8b88-4f3c75213ae3.png)

The solution we came up with was to replace "No Sensor" + X icon, with "Set Sensor" + question mark icon, which when clicked opens a sensor selection dialog (like that one the sensor tab except green).

**Comment by SteveFulton95** [comment]
Just to clarify, do we want all of the sensor labels clickable or just one that does not have a sensor?

**Comment by ehamner** [comment]
I think they could all be clickable.

**Comment by tasota** [comment]
Related to #6

**Comment by tasota** [comment]
probably want to resolve #86 first
