### ISSUE TITLE
Change the min/max labels as soon as a sensor is selected

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#71]
When configuring a relationship, the custom labels for min/max should be set as soon as the sensor is selected. 

So here, the user hasn't yet picked the sensor, but as soon as they do, the labels would change to go with the sensor selected
![robot-03-servosettings-link](https://cloud.githubusercontent.com/assets/24419423/22755546/9cc33758-ee11-11e6-9149-a81416face91.png)

**Comment by jenncross** [comment]
E.g. The word "maximum" would be set to be "bright" and the word "minimum"
would be set to be "dark" .... as soon as the student Sensor 1 (a light
sensor)

**Comment by lczito** [comment]
Currently, for the servos, this shows up only after you go in and individually set the endpoints, rather than after you select the sensor. It does not change at all for the LEDs
