### ISSUE TITLE
Pitch/Volume Control

### ISSUE THREAD

**Issue by lczito** [CMU-CREATE-Lab/flutter-app-android#72]
If you set up a link with the volume and then go to set up a link with the pitch, the buzzer stops working completely. If you just set up a link with the volume, it works and keeps a steady pitch. We have not tested doing just the pitch.

**Comment by jenncross** [comment]
I think there needs to be some sort of default behavior for when only a
pitch or only volume is set.

Something like:
A) If just pitch is linked, volume should become fixed at 100%
A) If just volume is linked, pitch should become fixed at 440hz

This would be easiest to represent if issue #48 (constant relationships)
was fixed.

**Comment by jenncross** [comment]
This is also connected or a duplicate of issue #54
