### ISSUE TITLE
Min/max popups should start at the current setting

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#77]
When setting the relationships, min/max popups should start with the current setting.

So for example, if I have this, and I click on the Bright Position, the popup that appears should start with the servo slider at 55
![robot-06-servosettings-positionsset](https://cloud.githubusercontent.com/assets/24419423/22756514/5a51d83a-ee15-11e6-8221-2efc5b8baae8.png)

**Comment by jenncross** [comment]
This seems like a bug - where the pop-up selector does not import/default to its last setting.
