### ISSUE TITLE
Add the output icon to the title of the relationship config popup

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#82]
Users in one group were confused about what output they were configuring in the relationship configuration popup. Add a small icon for the servo/LED/buzzer with the "Set up LED 1" title, ie "<icon> Set up LED 1".

**Comment by jenncross** [comment]
zeplin

**Comment by mo11yj** [comment]
Updated to include icon in header: 
Servo: https://zpl.io/Z1MGolJ
LED: https://zpl.io/FsrgJ
Speaker: https://zpl.io/Z1fNzY3

**Comment by pdille** [comment]
Fixed in commit 9a52305c
