### ISSUE TITLE
Adjust bottom buttons on relationship config popup

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#84]
Width: Make "remove link" button smaller and "save link" button bigger. Maybe 1/3 and 2/3 if feasible.

Color: Make both buttons grey with white text if there is no link (disabled, not clickable). When there is a link, make both buttons green with white text (enabled, clickable).

**Comment by mo11yj** [comment]
I would recommend changing the size of the buttons, but keeping the colors different, when the color is the same I fear that it reads too much like a single button. If the grey was being perceived as Inactive, we can explore other ways to indicate that it is active, but a secondary action.  Let me know which treatment you prefer and I can update all the screens in Zeplin. 

![screen shot 2017-02-18 at 9 30 12 pm](https://cloud.githubusercontent.com/assets/25698542/23098644/c645a3be-f621-11e6-84dc-a3cd965eaf0d.png)
![screen shot 2017-02-18 at 9 30 25 pm](https://cloud.githubusercontent.com/assets/25698542/23098645/c86e4fe2-f621-11e6-84d3-256b03ddff20.png)
![screen shot 2017-02-18 at 9 32 30 pm](https://cloud.githubusercontent.com/assets/25698542/23098646/c9fa84fc-f621-11e6-8756-e5b3490eb40f.png)

**Comment by ehamner** [comment]
I like the third one. @jenncross @lczito what do you guys think?

**Comment by ehamner** [comment]
I asked my six year old. She said they all look touchable except the green on white "because she can't see a line there" meaning if there was a line across above it it would look like a button and be touchable. That might be ok. I feel like we need the adults to know they can remove the link more than the kids and they are the ones being thrown off by the grey/disable feeling.

Staring at them a little, I started to feel like the bottom was two tabs rather than the Save Settings being a button. I think because the corners were square.

**Comment by mo11yj** [comment]
I like your daughter's idea, what if we went with something like this: 

![screen shot 2017-02-19 at 8 02 58 pm](https://cloud.githubusercontent.com/assets/25698542/23108659/7fa7b632-f6de-11e6-8d13-a9c7af73931b.png)

**Comment by ehamner** [comment]
I like that version.

**Comment by pdille** [comment]
Thanks for working on all this, Molly!

My concern with the white and green buttons is that it may be interpreted as tabs. It's fairly standard for tabs to have the active one be colored in and and the rest match the background (here being white) Now I guess the buttons being different sizes makes it less like a tab, but I could still see confusion occurring.

I'd avoid gray though, as already stated, since it could be interpreted as disabled. 

I know we wanted to change the wording of "Save Settings" to "Save Link" (which I've already done), so maybe that makes my concern above a mute point.

Anyway, my two cents. :-)

**Comment by mo11yj** [comment]
One other idea, use a lighter green rather than white or grey: 

![screen shot 2017-02-20 at 7 21 34 pm](https://cloud.githubusercontent.com/assets/25698542/23146119/f97f8da4-f7a1-11e6-846f-e642806690a6.png)

**Comment by ehamner** [comment]
I like this one as well. I think the light green is an improvement over the grey.

**Comment by mo11yj** [comment]
OK, I updated all the robot screens in Zeplin to the light green button treatment: https://zpl.io/Z1MGolJ

**Comment by jenncross** [comment]
Are we also combining this with graying out when the form is not complete as described in Issue #45  - or is that issue obsolete?

**Comment by pdille** [comment]
@jenncross Yes, we are.

Fixed in commit 62e542a1

**Comment by ehamner** [comment]
The version with the red-ish "remove link" button in release 1.0.3 is working for kids.
