### ISSUE TITLE
Fix "sensor values move in sync" bug (hardware)

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#85]
These two incidents could possibly be related hardware or firmware issues.

1) Dry Lavender Griffin was being demoed for GEMS. When the soil moisture sensor was placed in water, the other two sensors started started moving together (same reading), opposite the value of the soil moisture. See videos:

https://drive.google.com/file/d/0B6_-sEg9Mh9COU1KZlczaFhUNXM/view?usp=drivesdk

https://drive.google.com/file/d/0B6_-sEg9Mh9CNGdCWVN4TDNnTnM/view?usp=drivesdk

2) Galactic Moonstone Horse was being used in PD. Sound sensor in port 1 and light sensor in port 2. We used the app to simulate data then went back to live sensor readings. The two sensors starting moving in sync with the same reading. When we connected with a different kindle, the behavior continued. When we power cycled the flutter board, the board was better and the behavior could not be reproduced.

**Comment by ehamner** [comment]
Note to team: If you see the error when in the lab, leave the board plugged in and powered on and tell Josh so he can do some tests.

**Comment by JSchapiro** [comment]
While i was play around with some speckle boards, it happened. I was able to determine that the issue IS flutter side. Not app or BLE side.

**Comment by jenncross** [comment]
Fix with new board hopefully.
