### ISSUE TITLE
SVG to XML converter

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#89]
@pdille discovered a great tool that can convert SVG into XML for Android. So we can probably start replacing all of those images for nicer scalability.

**Comment by pdille** [comment]
For future needs of making an svg out of a png, go here: http://a-student.github.io/SvgToVectorDrawableConverter.Web/

Note: requires very slight tweaking to the output to work in Android.

**Comment by pdille** [comment]
This thread serves more to document the tool than being an actual issue, thus closing it.
