### ISSUE TITLE
How to fill out stats that overlap?

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#94]
The Filled-All stats screen from the design shows how to draw the labels for relatively distant values. How do we want to display these when the labels would otherwise be relatively close to one another?

Below is a screenshot from the screen as it currently looks in the code. For the first sensor, mode/max/min would all be at 100. I imagine they could either be spaced out on the same line or perhaps beneath one another on new lines, but I don't know what would look nicer or make more sense.

![screenshot_2017-02-22-15-05-05](https://cloud.githubusercontent.com/assets/9115672/23230394/c231eaa6-f911-11e6-9b76-1c4793cc8749.png)

**Comment by mo11yj** [comment]
Sorry for the delayed reply, not sure how I missed this, I think they should stack, I think that would be more clear than them lining up next to each other. Let me know if you would like me to mock this up, but it should be simple enough, I would stack them with 4-5 pixels between each.
