### ISSUE TITLE
Clean Up data log but still appears in list

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#96]
It goes away from the list after reopening the Data tab

**Comment by pdille** [comment]
Steps to reproduce:
1. Click Open Log and choose any log
2. Click Clean Up and choose the log you're viewing (though I don't think it matters what you select)
3. Click Clean Up again. You'll see the log you deleted still in the Clean Up Logs list

Note that clicking Open Log or Data Log tab will clear out the list.
