### ISSUE TITLE
Servo icons on Robot Activity overlap

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#97]
See attached image.

![screenshot_2017-02-24-09-49-06](https://cloud.githubusercontent.com/assets/9115672/23307750/a3241c22-fa76-11e6-894c-9b22716466fb.png)

**Comment by tasota** [comment]
for moving these icons, shifting down is probably better than shifting up

**Comment by pdille** [comment]
Fixed in commit dc0a3a2fb
